//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_16_3_2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST
    {
        public string ID { get; set; }
        public string UserName { get; set; }
        public string EquipmentType { get; set; }
        public string DateRequest { get; set; }
        public string Status { get; set; }
    }
}
